"""
SQLite-based local message buffer for HAMq Producer resilience.

Design rationale
----------------
The SQLite buffer is the core resilience mechanism that prevents message loss
during Kafka outages (broker restarts, rolling upgrades, network partitions).

Flow:
  1. ProducerService generates a message.
  2. The message is written to SQLite **before** any attempt to send it to Kafka.
  3. ResilientKafkaProducer tries to send the message.
     - On success  → mark_sent() is called.
     - On failure  → the message remains in the buffer with sent=0.
  4. A background flush loop retries all pending messages whenever Kafka
     becomes available again, preserving original message order.
  5. A housekeeping task periodically removes old sent messages to keep the
     database from growing unboundedly.

The SQLite file is stored on a Kubernetes PersistentVolume so it survives
container restarts as well.
"""

from __future__ import annotations

import json
import logging
import time
from typing import Any, Dict, List

import aiosqlite

from app.config import settings

logger = logging.getLogger(__name__)


class MessageBuffer:
    """
    Async SQLite-backed message buffer.

    Thread safety: all methods are async and must be called from the same
    asyncio event loop.  Do not share an instance across threads.
    """

    def __init__(self, db_path: str | None = None) -> None:
        """
        Parameters
        ----------
        db_path:
            Filesystem path for the SQLite file.
            Defaults to ``BUFFER_DB_PATH`` from settings.
        """
        self._db_path: str = db_path or settings.BUFFER_DB_PATH
        # Cached connection — opened lazily by initialize()
        self._db: aiosqlite.Connection | None = None

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    async def initialize(self) -> None:
        """
        Open the SQLite connection and create the messages table if it does
        not already exist.

        Must be called once before any other method.
        """
        logger.info("Opening SQLite buffer at %s", self._db_path)
        self._db = await aiosqlite.connect(self._db_path)

        # Enable WAL mode for better concurrent read/write performance
        await self._db.execute("PRAGMA journal_mode=WAL")

        # Create the buffer table.
        # - message_id  : UUID4, used to uniquely identify messages for dedup
        # - payload_json: full message JSON (includes sequence, timestamp, etc.)
        # - created_at  : Unix timestamp (float) for TTL-based cleanup
        # - sent        : 0 = pending, 1 = successfully delivered to Kafka
        await self._db.execute(
            """
            CREATE TABLE IF NOT EXISTS messages (
                message_id   TEXT PRIMARY KEY,
                payload_json TEXT NOT NULL,
                created_at   REAL NOT NULL,
                sent         INTEGER NOT NULL DEFAULT 0
            )
            """
        )
        # Index on (sent, created_at) to make get_pending() fast
        await self._db.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_messages_sent_created
            ON messages (sent, created_at)
            """
        )
        await self._db.commit()
        logger.info("SQLite buffer initialised")

    async def close(self) -> None:
        """Close the SQLite connection gracefully."""
        if self._db is not None:
            await self._db.close()
            self._db = None
            logger.info("SQLite buffer closed")

    # ------------------------------------------------------------------
    # Write operations
    # ------------------------------------------------------------------

    async def add(self, message: Dict[str, Any]) -> bool:
        """
        Persist a message to the buffer.

        The message dict is serialised to JSON.  If the buffer is already at
        ``BUFFER_MAX_SIZE`` the oldest pending message is dropped to make room
        (the new message is always accepted — we prefer to lose old messages
        over new ones in an overflow scenario).

        Parameters
        ----------
        message:
            The message dict as generated by ProducerService (must contain
            an ``id`` key used as the primary key).

        Returns
        -------
        bool
            True on success, False if the write failed.
        """
        if self._db is None:
            logger.error("Buffer not initialised; call initialize() first")
            return False

        try:
            # Enforce max buffer size by evicting the oldest pending message
            pending = await self.count_pending()
            if pending >= settings.BUFFER_MAX_SIZE:
                logger.warning(
                    "Buffer full (%d/%d); evicting oldest pending message",
                    pending,
                    settings.BUFFER_MAX_SIZE,
                )
                await self._db.execute(
                    """
                    DELETE FROM messages
                    WHERE message_id = (
                        SELECT message_id FROM messages
                        WHERE sent = 0
                        ORDER BY created_at ASC
                        LIMIT 1
                    )
                    """
                )

            await self._db.execute(
                """
                INSERT OR IGNORE INTO messages (message_id, payload_json, created_at, sent)
                VALUES (?, ?, ?, 0)
                """,
                (message["id"], json.dumps(message), time.time()),
            )
            await self._db.commit()
            return True

        except Exception as exc:
            logger.exception("Failed to add message %s to buffer: %s", message.get("id"), exc)
            return False

    async def mark_sent(self, message_id: str) -> None:
        """
        Mark a previously buffered message as successfully delivered.

        Parameters
        ----------
        message_id:
            UUID4 of the message to mark (matches the ``id`` field in the
            message dict and the ``message_id`` column).
        """
        if self._db is None:
            return

        await self._db.execute(
            "UPDATE messages SET sent = 1 WHERE message_id = ?",
            (message_id,),
        )
        await self._db.commit()

    # ------------------------------------------------------------------
    # Read operations
    # ------------------------------------------------------------------

    async def get_pending(self, limit: int = 100) -> List[Dict[str, Any]]:
        """
        Return up to *limit* unsent messages, ordered by creation time (FIFO).

        The caller is responsible for calling :meth:`mark_sent` after a
        successful Kafka send so that messages are not re-delivered.

        Parameters
        ----------
        limit:
            Maximum number of messages to return per call.

        Returns
        -------
        list of dict
            Deserialised message dicts.
        """
        if self._db is None:
            return []

        try:
            async with self._db.execute(
                """
                SELECT payload_json FROM messages
                WHERE sent = 0
                ORDER BY created_at ASC
                LIMIT ?
                """,
                (limit,),
            ) as cursor:
                rows = await cursor.fetchall()

            return [json.loads(row[0]) for row in rows]

        except Exception as exc:
            logger.exception("Failed to fetch pending messages: %s", exc)
            return []

    async def count_pending(self) -> int:
        """
        Return the number of messages in the buffer that have not yet been
        delivered to Kafka.

        Returns
        -------
        int
            Pending message count (0 if the buffer is uninitialised).
        """
        if self._db is None:
            return 0

        try:
            async with self._db.execute(
                "SELECT COUNT(*) FROM messages WHERE sent = 0"
            ) as cursor:
                row = await cursor.fetchone()
                return row[0] if row else 0
        except Exception as exc:
            logger.exception("Failed to count pending messages: %s", exc)
            return 0

    # ------------------------------------------------------------------
    # Housekeeping
    # ------------------------------------------------------------------

    async def cleanup_sent(self, max_age_seconds: float = 3600.0) -> int:
        """
        Delete sent messages that are older than *max_age_seconds*.

        This prevents the SQLite file from growing unboundedly.  The default
        retention of 1 hour gives operators enough time to inspect the data
        post-incident.

        Parameters
        ----------
        max_age_seconds:
            Messages older than this (by creation time) are deleted.

        Returns
        -------
        int
            Number of rows deleted.
        """
        if self._db is None:
            return 0

        cutoff = time.time() - max_age_seconds
        try:
            cursor = await self._db.execute(
                "DELETE FROM messages WHERE sent = 1 AND created_at < ?",
                (cutoff,),
            )
            await self._db.commit()
            deleted = cursor.rowcount
            if deleted:
                logger.debug("Buffer cleanup: deleted %d sent messages", deleted)
            return deleted
        except Exception as exc:
            logger.exception("Buffer cleanup failed: %s", exc)
            return 0
