apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hamq-test-orchestrator.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hamq-test-orchestrator.labels" . | nindent 4 }}
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  KAFKA_TOPIC: {{ .Values.kafka.topic | quote }}
  KAFKA_TLS_ENABLED: {{ .Values.kafka.tlsEnabled | quote }}
  COUNTER_MAX: {{ .Values.counter.max | quote }}
  FREQ_HZ: {{ .Values.counter.frequencyHz | quote }}
  AUTOSTART: {{ .Values.counter.autostart | quote }}
  CORS_ORIGINS: "*"
