apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hamq-controller.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hamq-controller.labels" . | nindent 4 }}
data:
  KAFKA_NAMESPACE: {{ .Values.controller.kafkaNamespace | quote }}
  KAFKA_CLUSTER_NAME: {{ .Values.controller.kafkaClusterName | quote }}
  TARGET_NAMESPACES: {{ .Values.controller.targetNamespaces | quote }}
  CHAOS_ENABLED: {{ .Values.chaos.enabled | quote }}
  CHAOS_INTERVAL_SECONDS: {{ .Values.chaos.intervalSeconds | quote }}
  CHAOS_MAX_PODS_PER_ROUND: {{ .Values.chaos.maxPodsPerRound | quote }}
  API_PORT: "8003"
