image:
  frontend:
    enabled: false
persistence:
  storageClass: local-path
resources:
  backend:
    requests:
      memory: 128Mi
      cpu: "50m"
    limits:
      memory: 256Mi
      cpu: "500m"
  frontend:
    requests:
      memory: 32Mi
      cpu: "25m"
    limits:
      memory: 64Mi
      cpu: "100m"
monitoring:
  enabled: false
  serviceMonitor:
    enabled: false
ingress:
  enabled: true
  className: traefik
  host: controller.hamq.test
imagePullSecrets:
  - name: ghcr-secret
