kafka:
  version: "4.1.0"
  replicas: 1
  config:
    defaultReplicationFactor: 1
    minInsyncReplicas: 1
    offsetsTopicReplicationFactor: 1
    transactionStateLogReplicationFactor: 1
    transactionStateLogMinIsr: 1
  storage:
    type: persistent-claim
    size: 2Gi
    storageClass: local-path
    deleteClaim: true
  resources:
    requests:
      memory: 512Mi
      cpu: "200m"
    limits:
      memory: 1Gi
      cpu: "1000m"
  jvmOptions:
    xmx: 256m
    xms: 256m
  listeners:
    tls:
      enabled: false
    external:
      enabled: false
topics:
  messages:
    replicas: 1
    config:
      minInsyncReplicas: "1"
  dlq:
    replicas: 1
certManager:
  enabled: false
monitoring:
  enabled: false
  serviceMonitor:
    enabled: false
