kafka:
  version: "4.1.0"
  replicas: 3
  config:
    defaultReplicationFactor: 3
    minInsyncReplicas: 2
    offsetsTopicReplicationFactor: 3
    transactionStateLogReplicationFactor: 3
    transactionStateLogMinIsr: 2
  storage:
    type: persistent-claim
    size: 5Gi
    storageClass: local-path
    deleteClaim: true
  resources:
    requests:
      memory: 512Mi
      cpu: "300m"
    limits:
      memory: 1Gi
      cpu: "1000m"
  jvmOptions:
    xmx: 384m
    xms: 384m
  listeners:
    tls:
      enabled: false
    external:
      enabled: false
  podAntiAffinity: required
topics:
  messages:
    replicas: 3
    config:
      minInsyncReplicas: "2"
  dlq:
    replicas: 3
certManager:
  enabled: false
monitoring:
  enabled: false
  serviceMonitor:
    enabled: false
